services:
  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: .
    container_name: expo_frontend
    ports:
      - "8081:3000"
    depends_on:
      - backend
    restart: always
